### ISSUE TITLE
Slight documentation comment regarding Hypra Load

### ISSUE THREAD

**Issue by Kugelblitz360** [thierer/sd2iec#6]
Docs currently say:

  Hypra-Load
  ----------
  Hypra-Load uses the ATN line for handshake, so it only works if no
  other device is connected to the IEC bus.

which is true for Hypra Load V1 (from 64'er 10/84), but not for V2.1 that was published in special issue 6/85 (which also has several other bugs fixed).

But: THANK YOU for giving Hypra Load some extra love after all these years.

Boris

**Comment by thierer** [comment]
I actually wasn't aware of that version, thanks for the heads-up! I'll have a look and might add support for it, if the protocol doesn't differ too much from the original. At the very least I'll mention it in the docs.

From a quick check (haven't looked at the code yet) it doesn't seem to special-case directory loading so that doesn't work?

> But: THANK YOU for giving Hypra Load some extra love after all these years.

Oh, thank **you**. Hypra-Load was quite the revelation for me, when it came out. My only question would be if you trolled us on purpose by making us type in multiple DATA lines of kernal code :smile:

**Comment by Kugelblitz360** [comment]
https://www.c64-wiki.de/wiki/Hypra-Load/Quellcode_2.1

I was pretty proud of my reuse of the filename to allow Uparrow-Star-Filename to autoload.

And as you may remember, my parents (and Karstens parents) landline phone number was in the listing. The stupidest thing Karsten and I ever did because of course the listing was slightly misprinted (one line unreadable).

1.0 in hindsight is a really bad version. We were young and there was a deadline.

**Comment by thierer** [comment]
Documentation updated and 2.1 support implemented in d51a9b67.
